server:
  port: 8000
kafka:
  topics:
    processed: processed-video
    streaming: streaming-video
  consumer:
    bootstrap-servers: 10.152.183.90:9094
    key-serializer: serializer
    value-serializer: serializer
    acks: all
    compression-type: gzip
    auto-offset-reset: earliest
mongodb:
  uri: mongodb://admin:admin@localhost:30332/admin?readPreference=primaryPreferred
  database: blue-mongodb
